# Generated by Django 5.0.2 on 2024-02-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=40)),
                ('venue', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('time', models.DateTimeField()),
                ('tickets', models.CharField(max_length=100)),
            ],
        ),
    ]
