# Generated by Django 5.0.2 on 2024-02-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandtour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(),
        ),
    ]
